Issue11/add lic 4
tohanss/DECIDE pull request #25
Opened 2024-01-29 13:39 UTC by angelicaengstrom

My proposal for issue #11 "There exists at least one set of three consecutive data points that are the vertices of a triangle with area greater than AREA1", this includes
* javadoc
* false and positive tests

Please review and suggest feedback

2024-01-29 22:59 UTC, tohanss requested changes
Looks good, just the line that shouldnt be commented out. Just wait for CI branch to be merged and we can check if the tests pass.

2024-01-29 22:59 UTC, tohanss commented on src/main/java/decide/LIC.java
> +        //CMV[3] = LIC_3();
Should not be commented out

2024-01-30 12:54 UTC, TerenceNg03 requested changes
Please merge CI from main first, so the check will run on this pr.

2024-01-30 16:59 UTC, tohanss commented on src/main/java/decide/LIC.java
> +        //CMV[3] = LIC_3();
We can fix this with #29

2024-01-30 18:54 UTC, TerenceNg03 approved these changes

2024-01-30 22:37 UTC, TerenceNg03 requested changes
It seems that you commit `.idea` and `libraries` which should be ignored?

2024-01-31 15:58 UTC, merged