Issue18/add lic 11
tohanss/DECIDE pull request #26
Opened 2024-01-29 14:12 UTC by angelicaengstrom

My proposal for issue #18 regarding LIC 11, this includes

* functioanlity for LIC 11

* javadoc
* false and positive tests

Please review and suggest feedback

2024-01-29 23:06 UTC, tohanss requested changes
Looks good, but similar to other PR with the comment.

2024-01-29 23:06 UTC, tohanss commented on src/main/java/decide/LIC.java
> +        //CMV[10] = LIC_10();
Should not be commented out

2024-01-30 12:54 UTC, TerenceNg03 requested changes
Please merge CI from main first, so the check will run on this pr.

2024-01-31 15:59 UTC, tohanss approved these changes

2024-01-31 15:59 UTC, TerenceNg03 commented on src/main/java/decide/LIC.java
> +        //CMV[10] = LIC_10();
Would be fixed later.

2024-01-31 16:13 UTC, merged