Issue22/add lic 15
tohanss/DECIDE pull request #27
Opened 2024-01-29 14:41 UTC by angelicaengstrom

My proposal for issue #18 regarding LIC 15, this includes

* functionality for LIC 15

* javadoc

* false and positive unit-tests

Please review and suggest feedback

2024-01-29 23:08 UTC, tohanss requested changes
Looks good! Just the commented out line

2024-01-29 23:08 UTC, tohanss commented on src/main/java/decide/LIC.java
> +        //CMV[14] = LIC_14();
Should not be commented out

2024-01-30 12:53 UTC, TerenceNg03 requested changes
Please merge CI from main first, so the check will run on this pr.

2024-01-31 15:59 UTC, TerenceNg03 commented on src/main/java/decide/LIC.java
> +        //CMV[14] = LIC_14();
Can be fixed later.

2024-01-31 16:23 UTC, tohanss approved these changes

2024-01-31 16:23 UTC, merged